### ISSUE TITLE
Criar tela para visualização dos cadastros

### ISSUE THREAD

**Issue by fraterblack** [Leacina/projeto-ed#19]
Uma vez que o usuário "Convidado" não pode editar ou excluir cadastros. É necessário criar uma tela para que ele possa visualizar as informações do cadastro.
Apartir das listagens é possível criar uma tela de visualização quando ele dar um duplo clica em alguma linha da JTable (Já coloquei um listener para duplo click lá)

**Comment by wilianx7** [comment]
Vou fazer isso. Na listagem do aluno, por exemplo, o usuário convidado poderá visualizar todas as informações do aluno ou somente algumas informações principais?

**Comment by fraterblack** [comment]
No caso do Usuário, não se deve-se visualizar a senha por questões de segurança
