### ISSUE TITLE
Método EditarDadosNoArquivo bugando TXT

### ISSUE THREAD

**Issue by wilianx7** [Leacina/projeto-ed#58]
Ao fazer uma edição de qualquer um dos cadastros (alunos, cidades, professores, etc) , os TXTs passam a salvar todos os dados na mesma linha, não havendo mais a quebra de linha tanto em novas edições quanto em novos cadastros. Para que a quebra de linha funcione novamente é preciso deletar o arquivo TXT correspondente.
A princípio isso não causa nenhum problema na execução do software, no entanto, as informações contidas nos TXTs ficam desorganizadas, pois ficam todas juntas na mesma linha.

Obs: aparentemente o problema ocorre nesse trecho do código:
FileOutputStream fileOut = new FileOutputStream(pegarDestinoArquivo(area));
fileOut.write(inputStr.getBytes());
fileOut.close();

**Comment by fraterblack** [comment]
Não consegui reproduzir esse erro.

**Comment by fraterblack** [comment]
Resolvido
