### ISSUE TITLE
Recolocar o papel de parede do programa ou remover o código comentado

### ISSUE THREAD

**Issue by fraterblack** [Leacina/projeto-ed#64]
Ou recolocamos o papel de parede no programa, ou devemos remover o código comentado e todas as dependências que tem no arquivo.

OBS: Se voltar a colocar o papel de parede, tem que diminuir a opacidade dele.

**Comment by AlissonSchmitz2** [comment]
Realizada alteração na opacidade de imagem, incluído o ícone e papel de parede.
